### ISSUE TITLE
How to distinguish between projects and companies?

### ISSUE THREAD

**Issue by okwme** [cosmos/jobs#1]
A lot of projects are being built by:
 * a single company with the same name as the project
 * a single company with a different name as the project
 * multiple companies with diffierent names as the project

How should we be recommending these various scenarios are all represented within the capabilities we currently have?

**Comment by taariq** [comment]
I think we should use the lens: "What behavior to we want to encourage?" We want to encourage as many users to create as many projects as possible that are hiring. As such, multiple projects can be claimed by their respective company controlled by a user. Our most valuable customer, which is the talent who wants many opportunities as possible from which they can choose or spend more time engaged in exploring. They should have many choices that are individual and unique for them to consume.
