### ISSUE TITLE
Blockchain technologies

### ISSUE THREAD

**Issue by cozfields** [cosmos/jobs#14]
To whom it may concern,

My name is Zac Fields. I am currently a press operator at a publicly traded company in the Northeast United States. This may be an unorthodox way to get in touch but I see blockchain as a bright future for everyone. One that will (eventually) change the world. 

I am the type of person who does not allow failure to stop them when they set their mind to something. And in the past few months I have set my mind on becoming a part of the blockchain technologies future. 

My problem is this. In the last 7 years I have gone from homeless to starting a family and paying off a house. I’ve come a long way, but am nowhere near my final long-term goals.

On the short-term side of things I want to go to school. For something like software engineering or information technologies. I can do this on student loans alone, but it will only cover enough for me to go as a “half-time” student as they called it. This is partially due to the fact of my age and financial bracket not qualifying me for any Pell grants.
If I am going to do this though, I would like to be a Full-time, fully committed student

I am reaching out to many blockchain teams to see if they would be interested in investing in future employees. One who does not take “No” for an answer, no matter how many times he hears it. A person who’s appetite for success is only fueled by any failures that come his way. Because I have failed. Many times. But it’s those failures that have shaped the person I am today. And the one I want to be for the tomorrow’s to come.

The majority of this email is copy/paste but I felt I needed to add something to the Cosmos Team as I believe your project as well as a few others are going to be an integral part of that future that I keep speaking about. I really hope to work with you moving forward, and to hear back from you soon.

Thanks and have a nice day!
Zac Fields

**Comment by taariq** [comment]
Thank you for your kind email effort. Please make sure to contribute to the Cosmos ecosystem so we can see the veracity of your actions as capable of surpassing such an eloquent introduction.

**Comment by cozfields** [comment]
My ability to create an eloquent introduction is about all I have to contribute at the moment unfortunately. I'm not going to lie and say I know even a little about how to contribute currently. This was just a general reach out attempt to try and gain the ability to get enough knowledge under my belt to play a large roll in communities such as cosmos as well as others. Maybe going to school isn't even necessary. I want to learn everything and anything about blockchain technologies. Let's face it most schools don't offer much in the way of that information anyway. Can you point me in the direction to get started finding it on my own?
