### ISSUE TITLE
Add optanon or similar cookie agreement system

### ISSUE THREAD

**Issue by okwme** [cosmos/jobs#4]
we've been recommended to include a cookie agreement like optanon ([acquired by onetrust](https://www.onetrust.com/blog/onetrust-acquires-opanon-expands-internationally/))

**Comment by taariq** [comment]
@toddsantoro you okay to take this one?

**Comment by toddsantoro** [comment]
> @toddsantoro you okay to take this one?

Yep.

**Comment by toddsantoro** [comment]
This feature has been added and pushed to production.

**Comment by taariq** [comment]
Thanks!
