### ISSUE TITLE
Proposal to open Arabic Telegram Community 

### ISSUE THREAD

**Issue by zaidaljammal** [cosmos/jobs#5]
Dear sir,

We are arabic crypto enthusiastic team 
and
we are looking to have a business/partnership "marketing" with Cosmos.

It's about creating an arabic telegram community for the project.

We notice that many Arabic people are asking about Cosmos project. 

We think if we establish Arabic community, it will grow the communication with Arabs .
Note.
There are 23 Country speaking Arabic Language as Mother language so this Community will target all people in this countries. 

Looking to hear from You.

Sincerely,
Zaid Aljammal

**Comment by taariq** [comment]
This is for the job board. You may want to check the Discord.
