### ISSUE TITLE
BUG? View counts all say "View Zero Times"

### ISSUE THREAD

**Issue by taariq** [cosmos/jobs#7]
View count on all job posting say **"Viewed 0 times"** FYI @toddsantoro

**Comment by toddsantoro** [comment]
This can be closed as we simply need to set up a jetpack account on the backend of the site and the data should start flowing. Once the account is set up I will confirm this is working. I set this up on my dev machine and the count was working as well as the social share buttons for the jobs so we will get both functionalities...

**Comment by taariq** [comment]
Thanks! closing!
