### ISSUE TITLE
BUG: Job marked as Filled on front-end still shows as listed.

### ISSUE THREAD

**Issue by taariq** [cosmos/jobs#8]
https://jobs.cosmos.network/job/remote-full-time-senior-front-end-engineer/ shows as still active even though it's **FILLED**

**Comment by toddsantoro** [comment]
@taariq this is completed. You can test it out by marking a job as filled and then look on the front end to see that it is not included in the list anymore.

**Comment by taariq** [comment]
Thanks. Closing!
