### ISSUE TITLE
research methods for improving job management

### ISSUE THREAD

**Issue by okwme** [cosmos/jobs#9]
Currently it is only possible for the original author of a job to delete it. It is possible for an admin to mark it as filled.

This issue is to try to gather relevant info  to improving the situation.

Priority should be to ensure all authors and not just OP have ability to mark as filled (not just admins either). Afterwards it would be good if all authors can also delete the job. After it could be interesting to extend the permission of an org owner to be able to also manage the jobs without having to explicitly be added as a job author (or automate the process of ensuring org authors are also job authors).

All combinations should be considered and paired with estimates for how complicated they would be to execute to ensure a good balance of sunk time with results.

**Comment by taariq** [comment]
FYI @toddsantoro
